MainBundle\Entity\Asignatura:
    type: entity
    repositoryClass: MainBundle\Repository\AsignaturaRepository
    
    table: asignatura
    indexes:
        fk_id_estudio:
            columns:
                - id_estudio
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: 'nueva asignatura'
    manyToOne:
        idEstudio:
            targetEntity: Estudio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estudio:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
