MainBundle\Entity\Estudio:
    type: entity
    repositoryClass: MainBundle\Repository\EstudioRepository
    
    table: estudio
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: 'nuevo estudio'
    lifecycleCallbacks: {  }
