MainBundle\Entity\Profesor:
    type: entity
    repositoryClass: MainBundle\Repository\ProfesorRepository
    
    table: profesor
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: 'nuevo profesor'
    lifecycleCallbacks: {  }
